"""Write Google's official landmark references for the SDK integration tests.

Integration tests run on a phone, a simulator or an emulator, where the
package's JSON fixture is out of reach, so the points they compare against are
generated into Dart from test/fixtures/landmark_tasks/official_reference.json.
Rerun after regenerating that fixture, then run dart format on the output.
"""
import array
import gzip
import json
from pathlib import Path

GALLERY = Path(__file__).resolve().parents[1]
FIXTURE = (GALLERY.parent / 'packages/mediapipe-task-vision/test/fixtures/'
           'landmark_tasks/official_reference.json')
OUTPUT = GALLERY / 'integration_test/support/official_landmark_references.dart'
DETECTIONS = GALLERY / 'integration_test/support/official_detection_references.dart'
MASKS = GALLERY / 'integration_test/support/official_mask_references.dart'
FIXTURES = FIXTURE.parents[1]
# Gallery sample name for each fixture file the references decoded.
SAMPLE_NAMES = {'landmark-ex1.jpg': 'portrait.jpg',
                'group-shot-bounding-box-ex1.jpeg': 'group.jpeg'}

# (task, sample file, result field per part). File inputs, where the SDKs
# decode the same JPEG the reference decoded, and the upright pixels turned
# by rotation_degrees, keyed '<task>@<degrees>'.
CASES = [
    ('pose', 'pose.jpg', {'pose': 'pose_landmarks'}),
    ('gesture', 'thumb_up.jpg', {'hand': 'hand_landmarks'}),
    ('holistic', 'pose.jpg', {'pose': 'pose_landmarks',
                              'left_hand': 'left_hand_landmarks',
                              'right_hand': 'right_hand_landmarks'}),
]


def points(value):
    # Multi-subject tasks nest one list per subject; the samples have one.
    if value and isinstance(value[0], list):
        (value,) = value
    return ', '.join(f"({p['x']:.6f}, {p['y']:.6f})" for p in value)


def main():
    fixture = json.loads(FIXTURE.read_text())
    lines = [
        '// Generated by tool/generate_sdk_references.py from the vision',
        "// package's test/fixtures/landmark_tasks/official_reference.json",
        "// (Google's mediapipe==1.0.0 wheel, CPU). Do not edit by hand.",
        '',
        '/// Image landmarks (x, y) per part, keyed by task then part.',
        'const officialLandmarkReferences = <String, Map<String, List<(double, double)>>>{',
    ]
    for task, file, parts in CASES:
        for kind in ('file', 'rotated'):
            case = next(c for c in fixture['cases']
                        if c['task'] == task and c['input'] == kind and c['file'] == file)
            key = task if kind == 'file' else f"{task}@{case['rotation_degrees']}"
            lines.append(f"  '{key}': {{")
            for part, field in parts.items():
                lines.append(f"    '{part}': [{points(case['result'][field])}],")
            lines.append('  },')
    lines.append('};')
    OUTPUT.write_text('\n'.join(lines) + '\n')
    print(f'Wrote {OUTPUT.relative_to(GALLERY)}')
    write_detections()
    write_masks()


def detection(case):
    boxes = []
    for d in case['detections']:
        box = d['bounding_box']
        top = d['categories'][0]
        name = top['category_name']
        boxes.append(f"(left: {box['origin_x']}, top: {box['origin_y']}, "
                     f"right: {box['origin_x'] + box['width']}, "
                     f"bottom: {box['origin_y'] + box['height']}, "
                     f"score: {top['score']:.6f}, "
                     f"name: {'null' if name is None else repr(name)})")
    return ', '.join(boxes)


def write_detections():
    lines = [
        '// Generated by tool/generate_sdk_references.py from the vision',
        "// package's test/fixtures (Google's mediapipe==1.0.0 wheel, CPU).",
        '// Do not edit by hand.',
        '',
        'typedef OfficialBox = ({',
        '  int left,',
        '  int top,',
        '  int right,',
        '  int bottom,',
        '  double score,',
        '  String? name,',
        '});',
        '',
        '/// Detections per gallery sample, keyed by task then sample.',
        'const officialDetectionReferences = <String, Map<String, List<OfficialBox>>>{',
    ]
    for task, folder in (('face_detector', 'face_detection'),
                         ('object_detector', 'object_detection')):
        fixture = json.loads((FIXTURES / folder / 'official_reference.json').read_text())
        lines.append(f"  '{task}': {{")
        for case in fixture['cases']:
            if case.get('file') in SAMPLE_NAMES:
                lines.append(f"    '{SAMPLE_NAMES[case['file']]}': [{detection(case)}],")
        lines.append('  },')
    lines.append('};')
    image = json.loads((FIXTURES / 'image_tasks/official_reference.json').read_text())
    case = next(c for c in image['cases']
                if c['task'] == 'classifier' and c['input'] == 'file')
    categories = case['result']['classifications'][0]['categories']
    lines += [
        '',
        f"/// Top {len(categories)} image classes for portrait.jpg "
        f"(max_results {case['options']['max_results']}).",
        'const officialClassifierReference = <(String, double)>[',
        *[f"  ({c['category_name']!r}, {c['score']:.6f})," for c in categories],
        '];',
    ]
    embedding = next(c for c in image['cases']
                     if c['task'] == 'embedder' and c['input'] == 'file'
                     and not c['options']['l2_normalize'] and not c['options']['quantize'])
    values = embedding['result']['embeddings'][0]['embedding']
    lines += [
        '',
        f"/// portrait.jpg's float embedding ({len(values)} values, not normalized).",
        'const officialEmbedderReference = <double>[',
        *[f'  {v:.7g},' for v in values],
        '];',
    ]
    DETECTIONS.write_text('\n'.join(lines) + '\n')
    print(f'Wrote {DETECTIONS.relative_to(GALLERY)}')


def coarse_record(width, height, coarse):
    confidence = ', '.join(
        f'{index}: [{", ".join("[" + ", ".join(f"{v:g}" for v in row) + "]" for row in grid)}]'
        for index, grid in coarse.get('confidence_grids', {}).items())
    category = ', '.join('[' + ', '.join(map(str, row)) + ']'
                         for row in coarse['category_grid'])
    shares = ', '.join(f'{k}: {v:g}' for k, v in coarse['category_shares'].items())
    return (f'(width: {width}, height: {height}, '
            f'confidence: <int, List<List<double>>>{{{confidence}}}, '
            f'category: <List<int>>[{category}], shares: <int, double>{{{shares}}})')


def write_masks():
    fixture = json.loads((FIXTURES / 'segmenter_tasks/official_reference.json').read_text())
    files = [c for c in fixture['cases'] if c['input'] == 'file']
    image = next(c for c in files if c['task'] == 'image'
                 and c['options']['output_confidence_masks']
                 and c['options']['output_category_mask'])
    # The legacy task records its confidence and category masks separately.
    legacy = {}
    for case in files:
        if case['task'] == 'interactive':
            legacy.update(case['coarse'])
    keypoint = next(c for c in files if c['task'] == 'interactive')['keypoint']
    lines = [
        '// Generated by tool/generate_sdk_references.py from the vision',
        "// package's test/fixtures/segmenter_tasks/official_reference.json",
        "// (Google's mediapipe==1.0.0 wheel, CPU). Do not edit by hand.",
        '',
        '/// A mask reduced to grids: cell means of each confidence mask that',
        '/// reaches 0.5, keyed by mask index, and the class at each cell centre',
        "/// of the category mask, with each class's share of the image.",
        'typedef OfficialMasks = ({',
        '  int width,',
        '  int height,',
        '  Map<int, List<List<double>>> confidence,',
        '  List<List<int>> category,',
        '  Map<int, double> shares,',
        '});',
        '',
        "/// Image Segmenter (DeepLab-v3) on portrait.jpg.",
        f"const officialSegmenterReference = {coarse_record(image['width'], image['height'], image['coarse'])};",
        '',
        f"/// Legacy Interactive Segmenter (MagicTouch) on portrait.jpg from the",
        f"/// keypoint ({keypoint['x']}, {keypoint['y']}).",
        f"const officialInteractiveLegacyReference = {coarse_record(image['width'], image['height'], legacy)};",
    ]
    landmarks = json.loads(FIXTURE.read_text())
    means = []
    for task in ('pose', 'holistic'):
        for kind in ('file', 'rotated'):
            # The first matching case has default thresholds, as in CASES.
            case = next(c for c in landmarks['cases'] if c['task'] == task
                        and c['input'] == kind and c['file'] == 'pose.jpg')
            mask = case['result'].get('segmentation_mask') or case['result']['segmentation_masks'][0]
            key = task if kind == 'file' else f"{task}@{case['rotation_degrees']}"
            means.append(f"'{key}': {mask['mean']:.6f}")
    interactive = json.loads(
        (FIXTURES / 'interactive_segmentation/official_reference.json').read_text())
    cat = next(c for c in interactive['cases'] if c['name'] == 'file-cat')
    values = array.array('f', gzip.decompress(
        (FIXTURES / 'interactive_segmentation' / cat['mask']).read_bytes()))
    width, height = cat['width'], cat['height']
    columns, rows = 16, 8
    grid = []
    for r in range(rows):
        row = []
        for c in range(columns):
            cell = [values[y * width + x]
                    for y in range(r * height // rows, (r + 1) * height // rows)
                    for x in range(c * width // columns, (c + 1) * width // columns)]
            row.append(f'{sum(cell) / len(cell):.4f}')
        grid.append('[' + ', '.join(row) + ']')
    (x, y), = cat['strokes'][0]['points']
    lines += [
        '',
        "/// Google's stateful MagicTouch mask of animals.jpg for one positive",
        f'/// stroke at ({x}, {y}): cell means on a {columns} x {rows} grid, the mean,',
        '/// and the share of pixels above 0.5.',
        'const officialInteractiveReference = (',
        f'  width: {width},',
        f'  height: {height},',
        f'  point: ({x}, {y}),',
        f"  grid: <List<double>>[{', '.join(grid)}],",
        f"  mean: {cat['mean']:.6f},",
        f"  foreground: {cat['foreground_pixels'] / (width * height):.6f},",
        ');',
    ]
    lines += [
        '',
        '/// Mean pose segmentation mask value on pose.jpg, upright and turned as in',
        '/// officialLandmarkReferences.',
        f"const officialPoseMaskMeans = <String, double>{{{', '.join(means)}}};",
    ]
    MASKS.write_text('\n'.join(lines) + '\n')
    print(f'Wrote {MASKS.relative_to(GALLERY)}')


if __name__ == '__main__':
    main()
