"""Cross-build the combined open-source task runtime for arm64 iOS.

Builds the same `//mediapipe/tasks/c:libmediapipe` target the macOS runtime and
Google's own wheel use, so one library carries every open-source task instead of
one dylib per task, which each re-embedded the whole graph runtime.

This produces local development artifacts. Run tool/test_ios_simulator.py to
verify inference inside Flutter; macOS cannot load simulator dylibs directly.
No upstream source is modified and no artifact is uploaded.
"""
import argparse
import hashlib
import json
from pathlib import Path
import platform
import re
import shutil

from build_native import (
    FORCED, PACKAGE, REPO, REVISION, SOURCE, OPENCV_REVISION, TARGET,
    build_opencv, capture, exported_functions, linked_packages, run,
)

# On iOS the upstream `libmediapipe` alias falls through to its default branch
# and names the output libmediapipe.so; the bytes are a Mach-O dylib regardless.
BUILT_NAME = 'libmediapipe.so'
LIBRARY = 'libmediapipe.dylib'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--sdk', choices=('iphonesimulator', 'iphoneos'),
                        default='iphonesimulator',
                        help='Device slices are build-checked, not inference-validated.')
    parser.add_argument('--output-dir', type=Path)
    parser.add_argument('--jobs', type=int, default=8)
    parser.add_argument('--source-dir', type=Path,
                        default=REPO / 'build/codex-tmp/mediapipe-native')
    parser.add_argument('--bazel-cache', type=Path,
                        default=REPO / 'build/codex-tmp/bazel')
    parser.add_argument('--opencv-root', type=Path,
                        default=REPO / 'build/codex-tmp')
    args = parser.parse_args()
    if args.jobs < 1:
        raise SystemExit('--jobs must be positive.')
    if platform.system() != 'Darwin' or platform.machine() != 'arm64':
        raise SystemExit('This cross-build requires an Apple Silicon Mac with Xcode.')
    source = args.source_dir.resolve()
    if not source.exists():
        source.parent.mkdir(parents=True, exist_ok=True)
        run(['git', 'clone', '--depth', '1', '--branch', 'v1.0.0', SOURCE, str(source)])
    if capture(['git', 'rev-parse', 'HEAD'], source) != REVISION:
        raise SystemExit('Refusing unpinned MediaPipe source.')
    if capture(['git', 'diff', '--name-only', 'HEAD'], source):
        raise SystemExit('Refusing modified MediaPipe source.')
    simulator = args.sdk == 'iphonesimulator'
    cpu = 'ios_sim_arm64' if simulator else 'ios_arm64'
    opencv, configuration = build_opencv(args.opencv_root.resolve(), ios_sdk=args.sdk,
                                         jobs=args.jobs)
    packages = linked_packages(source)
    exports = exported_functions(source, packages)
    constructors = sorted(name for name in exports
                          if re.fullmatch(r'Mp\w+Create', name))
    tasks = sorted(package.rsplit('/', 1)[-1] for package in packages
                   if re.fullmatch(r'mediapipe/tasks/c/(?:vision|text|audio)/'
                                   r'(?!core$)\w+', package))
    print(f'{len(packages)} linked packages, {len(exports)} exported functions, '
          f'{len(tasks)} tasks: {", ".join(tasks)}', flush=True)
    flags = [
        '--config=ios', f'--cpu={cpu}', '--ios_minimum_os=13.0',
        f'--platforms=@build_bazel_apple_support//platforms:{cpu}',
        '--extra_toolchains=@@apple_support~~apple_cc_configure_extension~local_config_apple_cc_toolchains//:all',
        '-c', 'opt', '--strip=always', f'--jobs={args.jobs}',
        '--repo_env=HERMETIC_PYTHON_VERSION=3.12',
        '--define=MEDIAPIPE_DISABLE_GPU=1',
        # The simulator executes on the host CPU. Apple's SME support does
        # not allow the non-streaming SVE generated by Clang in these wrappers.
        '--per_file_copt=external/KleidiAI/.*[.]c@-fno-vectorize,-fno-slp-vectorize',
        '--linkopt=-Wl,-headerpad_max_install_names',
        '--linkopt=-Wl,-exported_symbol,_Mp*',
    ]
    # One link keeps every task's entry points: nothing references them from
    # inside the library, so each constructor is forced undefined explicitly.
    if FORCED not in exports:
        raise SystemExit(f'{FORCED} is no longer an exported entry point.')
    flags.extend(f'--linkopt=-Wl,-u,_{name}' for name in [*constructors, FORCED])
    run(['bazelisk', f'--output_user_root={args.bazel_cache.resolve()}',
         'build', *flags, f'--override_repository=ios_opencv={opencv}', TARGET], source)
    built = source / 'bazel-bin/mediapipe/tasks/c' / BUILT_NAME
    build_info = capture(['xcrun', 'vtool', '-show-build', str(built)])
    expected_platform = 'IOSSIMULATOR' if simulator else 'IOS'
    if (not re.search(rf'^\s*platform\s+{expected_platform}\s*$', build_info, re.MULTILINE) or
            capture(['xcrun', 'lipo', '-archs', str(built)]) != 'arm64'):
        raise SystemExit(f'Not an arm64 {args.sdk} dylib: {build_info}')
    minimum_os = re.search(r'^\s*minos\s+(\d+(?:\.\d+)+)\s*$', build_info, re.MULTILINE)
    if minimum_os is None:
        raise SystemExit(f'Missing deployment target in {build_info}')
    exported = {name.lstrip('_') for name in
                capture(['xcrun', 'nm', '-gjU', str(built)]).splitlines()}
    missing = sorted(exports - exported)
    if missing:
        raise SystemExit(f'Missing C API exports in {built}: {missing}')
    for dependency in capture(['otool', '-L', str(built)]).splitlines()[2:]:
        name = dependency.strip().split(' (', 1)[0]
        if not name.startswith(('/System/Library/', '/usr/lib/')):
            raise SystemExit(f'Non-system dependency: {name}')
    target = 'ios-simulator' if simulator else 'ios'
    output = args.output_dir or PACKAGE / f'build/native/{target}/arm64'
    output.mkdir(parents=True, exist_ok=True)
    destination = output / LIBRARY
    temporary = output / f'{LIBRARY}.tmp'
    shutil.copyfile(built, temporary)
    temporary.replace(destination)
    manifest = dict(
        source=SOURCE, revision=REVISION, version='1.0.0', target=TARGET,
        platform='ios', architecture='arm64', ios_sdk=args.sdk,
        # Apple clang floors the arm64 simulator link target to iOS 14.
        # Record the binary's requirement, not just the requested flag.
        minimum_os=minimum_os.group(1), requested_minimum_os='13.0',
        delegates=['cpu'], flags=flags, tasks=tasks,
        opencv_revision=OPENCV_REVISION, opencv_configuration=configuration,
        sha256=hashlib.sha256(destination.read_bytes()).hexdigest(),
        bytes=destination.stat().st_size,
        bazel_version=(source / '.bazelversion').read_text().strip(),
        xcode=capture(['xcodebuild', '-version']), build_info=build_info,
        validation=('Architecture/exports/dependencies checked; run Flutter simulator tests.'
                    if simulator else 'Architecture/exports/dependencies checked; '
                    'physical-device inference has not been validated.'),
    )
    (output / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    for name in ('LICENSE', 'NOTICE'):
        shutil.copyfile(PACKAGE / 'third_party' / name, output / name)
    licenses = output / 'opencv-licenses'
    shutil.copytree(opencv / 'share/licenses/opencv4', licenses, dirs_exist_ok=True)
    shutil.copyfile(args.opencv_root / 'opencv/LICENSE', licenses / 'LICENSE')
    shutil.copyfile(PACKAGE / 'third_party/OPENCV_CAROTENE_NOTICES', licenses / 'CAROTENE_NOTICES')
    print(f'{args.sdk} artifact: {destination} '
          f'({destination.stat().st_size} bytes, {len(exports)} exports)', flush=True)


if __name__ == '__main__':
    main()
